name: chocolatine

on:
  push:
  pull_request:

jobs:
  build:
    if: |
      github.event_name == 'push'
      && !startsWith(github.ref, 'refs/heads/no-ga/')
      && github.repository != 'mirror/repo'
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v4

      - name: Check Repo with banana
        run: banana-check-repo . > errors.txt
            EXIT_CODE=$?
            if [ $EXIT_CODE -ne 0 ]; then
              while IFS= read -r line; do
                echo "$line"
              done < errors.txt
            fi

      - name: Compile it
        run: make

      - name: Clean
        run: make clean
